# config / packages / vich_uploader.yaml ou app / config / config.yml
vich_uploader :
  db_driver : orm

  mappings :
    product_image :
      uri_prefix : / uploads / images / medicaments /
      upload_destination : ' % kernel.project_dir% / public / uploads / images / medicaments / '



