vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /assets/images/medicament
            upload_destination: '%kernel.project_dir%/public/assets/images/medicament'
