<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL9txi79\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL9txi79/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL9txi79.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL9txi79\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL9txi79\App_KernelDevDebugContainer([
    'container.build_hash' => 'L9txi79',
    'container.build_id' => '9c5380c6',
    'container.build_time' => 1610369216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL9txi79');
