<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxfNG4I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxfNG4I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxfNG4I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxfNG4I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxfNG4I\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxfNG4I',
    'container.build_id' => 'b6f0b6f5',
    'container.build_time' => 1606478597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxfNG4I');
