<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIjZKFm3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIjZKFm3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIjZKFm3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIjZKFm3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIjZKFm3\App_KernelDevDebugContainer([
    'container.build_hash' => 'IjZKFm3',
    'container.build_id' => '3f40c0bd',
    'container.build_time' => 1610623378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIjZKFm3');
